export const strings = {
  appTitle: 'Terminal Quest',
  landingTagline: 'Learn Linux by actually using it.',
  startPlaying: 'Start playing',
  startPlayingBusy: 'Waking up Tux…',
  startPlayingError: "Couldn't start your session. Check the server and try again.",
  healthOk: 'Server is up',
  fakeTerminalPrompt: 'player@tq:~$',
  fakeTerminalCommand: 'whoami',
  fakeTerminalOutput: 'future sysadmin',
  mapTitle: 'World map',
  mapLoading: 'Loading your quest…',
  mapError: "Couldn't load the map. Check the server and try again.",
  mapRetry: 'Try again',
  mapEmptyWorld: 'No levels here yet — check back soon.',
  levelLocked: 'Locked',
  levelCompleted: 'Completed',
  levelAvailable: 'Available',
  rankLabel: 'Rank',
  streakLabel: 'day streak',
  navSpellbook: 'Spellbook',
  navSkills: 'Skills',
  navProfile: 'Profile',
  navSettings: 'Settings',
  navMap: 'Map',
  levelPageTitle: 'Level',
  levelStarting: 'Waking up your sandbox…',
  levelLoadError: "Couldn't start this level.",
  levelRetry: 'Try again',
  levelBackToMap: 'Back to map',
  terminalLabel: 'Terminal',
  terminalLeave: 'Leave terminal',
  connectionLive: 'Connected',
  connectionStarting: 'Connecting…',
  connectionReconnecting: 'Reconnecting…',
  connectionClosed: 'Disconnected',
  connectionCompleted: 'Completed',
  missionTab: 'Mission',
  objectivesTitle: 'Objectives',
  bonusLabel: 'bonus',
  objectiveDone: 'done',
  objectivePending: 'pending',
  hintButton: 'Need a hint? (−5% XP)',
  hintButtonBusy: 'Asking Tux…',
  hintsLeft: 'hints left',
  noHintsLeft: 'No hints left.',
  resetLevel: 'Reset level',
  resetConfirm: 'Reset? Your sandbox gets a fresh seed and current progress is lost.',
  resetConfirmYes: 'Yes, reset',
  resetConfirmNo: 'Keep playing',
  leaveLevel: 'Leave level',
  completeTitle: 'Level complete!',
  completeXp: 'XP earned',
  completeSkills: 'New skills',
  completeExplain: 'What just happened?',
  completeBadges: 'New badges',
  nextLevel: 'Next level',
  replayLevel: 'Replay for rank',
  objectiveCompleteAnnouncement: 'Objective complete:',
  tuxThinking: 'Tux is thinking…',
  xpToNext: 'XP to next level',
  comingSoon: 'arrives in',
} as const;
