export const strings = {
  appTitle: 'Terminal Quest',
  landingTagline: 'Learn Linux by actually using it.',
  startPlaying: 'Start playing',
  startPlayingBusy: 'Waking up Tux…',
  startPlayingError: "Couldn't start your session. Check the server and try again.",
  healthOk: 'Server is up',
  fakeTerminalPrompt: 'player@tq:~$',
  fakeTerminalCommand: 'whoami',
  fakeTerminalOutput: 'future sysadmin',
  mapTitle: 'World map',
  mapLoading: 'Loading your quest…',
  mapError: "Couldn't load the map. Check the server and try again.",
  mapRetry: 'Try again',
  mapEmptyWorld: 'No levels here yet — check back soon.',
  levelLocked: 'Locked',
  levelCompleted: 'Completed',
  levelAvailable: 'Available',
  rankLabel: 'Rank',
  streakLabel: 'day streak',
  navSpellbook: 'Spellbook',
  navSkills: 'Skills',
  navProfile: 'Profile',
  navSettings: 'Settings',
  navMap: 'Map',
  levelPageTitle: 'Level',
  levelStarting: 'Waking up your sandbox…',
  levelLoadError: "Couldn't start this level.",
  levelRetry: 'Try again',
  levelBackToMap: 'Back to map',
  terminalLabel: 'Terminal',
  terminalLeave: 'Leave terminal',
  connectionLive: 'Connected',
  connectionStarting: 'Connecting…',
  connectionReconnecting: 'Reconnecting…',
  connectionClosed: 'Disconnected',
  connectionCompleted: 'Completed',
  missionTab: 'Mission',
  objectivesTitle: 'Objectives',
  bonusLabel: 'bonus',
  objectiveDone: 'done',
  objectivePending: 'pending',
  hintButton: 'Need a hint? (−5% XP)',
  hintButtonBusy: 'Asking Tux…',
  hintsLeft: 'hints left',
  noHintsLeft: 'No hints left.',
  resetLevel: 'Reset level',
  resetConfirm: 'Reset? Your sandbox gets a fresh seed and current progress is lost.',
  resetConfirmYes: 'Yes, reset',
  resetConfirmNo: 'Keep playing',
  leaveLevel: 'Leave level',
  completeTitle: 'Level complete!',
  completeXp: 'XP earned',
  completeSkills: 'New skills',
  completeExplain: 'What just happened?',
  completeBadges: 'New badges',
  nextLevel: 'Next level',
  replayLevel: 'Replay for rank',
  objectiveCompleteAnnouncement: 'Objective complete:',
  tuxThinking: 'Tux is thinking…',
  xpToNext: 'XP to next level',
  comingSoon: 'arrives in',
  pageLoading: 'Loading…',
  pageError: "Couldn't load this page. Check the server and try again.",
  spellbookTitle: 'Spellbook',
  spellbookSearch: 'Search skills, commands, notes…',
  spellbookEmpty: 'No spells yet — complete levels to unlock skills.',
  spellbookNoMatch: 'No skills match your search.',
  noteLabel: 'Personal note',
  noteSave: 'Save note',
  noteSaved: 'Saved',
  exportSpellbook: 'Export markdown',
  exportFailed: "Couldn't export the spellbook.",
  skillsTitle: 'Skills',
  skillsMastered: 'mastered',
  skillsUses: 'uses',
  skillsPrereqs: 'Requires',
  skillsEmpty: 'No skills discovered yet — complete levels to learn.',
  profileTitle: 'Profile',
  displayNameLabel: 'Display name',
  editName: 'Edit name',
  saveName: 'Save',
  cancelEdit: 'Cancel',
  saveFailed: "Couldn't save. Try again.",
  statsTitle: 'Stats',
  statLevelsDone: 'Levels completed',
  statCompletions: 'Total completions',
  statHintsUsed: 'Hints used',
  statStreak: 'Day streak',
  statXp: 'Total XP',
  badgesTitle: 'Badges',
  badgeLocked: 'Locked',
  settingsTitle: 'Settings',
  fontSizeLabel: 'Font size',
  fontSizeNormal: 'Normal',
  fontSizeLarge: 'Large',
  fontSizeXlarge: 'Extra large',
  highContrastLabel: 'High contrast',
  reducedMotionLabel: 'Reduce motion',
  resetProgress: 'Reset progress',
  resetProgressConfirm:
    'Erase all completions, XP, badges, and streaks? Your name and notes are kept.',
  hintsTab: 'Hints',
  notesTab: 'Notes',
  notesEmpty: 'No notes for this level yet — notes you save in the Spellbook appear here.',
  openSpellbook: 'Open Spellbook',
  keybarLabel: 'Terminal keys',
  ctrlArmed: 'Ctrl armed — next letter sends a control code',
} as const;
