export const strings = {
  appTitle: 'Terminal Quest',
  landingTagline: 'Learn Linux by actually using it.',
  startPlaying: 'Start playing',
  startPlayingBusy: 'Waking up Tux…',
  startPlayingError: "Couldn't start your session. Check the server and try again.",
  healthOk: 'Server is up',
  fakeTerminalPrompt: 'player@tq:~$',
  fakeTerminalCommand: 'whoami',
  fakeTerminalOutput: 'future sysadmin',
  mapTitle: 'World map',
  mapLoading: 'Loading your quest…',
  mapError: "Couldn't load the map. Check the server and try again.",
  mapRetry: 'Try again',
  mapEmptyWorld: 'No levels here yet — check back soon.',
  levelLocked: 'Locked',
  levelCompleted: 'Completed',
  levelAvailable: 'Available',
  rankLabel: 'Rank',
  streakLabel: 'day streak',
  navSpellbook: 'Spellbook',
  navSkills: 'Skills',
  navProfile: 'Profile',
  navSettings: 'Settings',
  navMap: 'Map',
  levelPageTitle: 'Level',
  xpToNext: 'XP to next level',
  comingSoon: 'arrives in',
} as const;
